### ISSUE TITLE
RxJs issue

### ISSUE THREAD

**Issue by nishbat** [apoterenko/ngx-dynamic-template#48]
Hi 

**I am getting this error.**

testpage:44 Error: (SystemJS) XHR error (404 Not Found) loading http://nitronet/static/scripts/vendor/ang/rxjs
	Error: XHR error (404 Not Found) loading http://nitronet/static/scripts/vendor/ang/rxjs
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:486:38)
	Error loading http://nitronet/static/scripts/vendor/ang/rxjs as "rxjs" from http://nitronet/static/scripts/vendor/ang/ngx-dynamic-template/bundles/ngx-dynamic-template.umd.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:486:38)
	Error loading http://nitronet/static/scripts/vendor/ang/rxjs as "rxjs" from http://nitronet/static/scripts/vendor/ang/ngx-dynamic-template/bundles/ngx-dynamic-template.umd.js

**Below is my package.json file**

{
  "name": "myproject",
  "version": "1.0.0",
"peerDependencies": {
    "@angular/core": "~4.1.3",
    "@angular/common": "~4.1.3",
    "@angular/compiler": "~4.1.3",
    "@angular/platform-browser": "~4.1.3",
    "@angular/http": "~4.1.3",

    "core-js": "^2.4.1",
    "rxjs": "~5.1.0",
    "zone.js": "~0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.3",
    "@angular/core": "~4.1.3",
    "@angular/common": "~4.1.3",
    "@angular/compiler": "~4.1.3",
    "@angular/platform-browser": "~4.1.3",
    "@angular/http": "~4.1.3",
    "@angular/forms": "~4.1.3",
    "@angular/platform-browser-dynamic": "~4.1.3",
    "angular-in-memory-web-api": "~0.2.4",
    "ngx-dynamic-template": "2.1.24",

    "@types/core-js": "~0.9.35",
    "@types/node": "~6.0.38",

    "core-js": "^2.4.1",
    "rxjs": "~5.1.0",
    "zone.js": "~0.8.4",

    "rollup": "~0.36.3",
    "rollup-plugin-commonjs": "~7.0.0",
    "rollup-plugin-includepaths": "~0.1.8",
    "rollup-plugin-uglify": "~1.0.1",

    "es6-shim": "^0.35.3",
    "gulp": "^3.9.1",
    "reflect-metadata": "^0.1.3",
    "systemjs": "^0.19.40"
  }
}

**Comment by nishbat** [comment]
It was actually issue with RxJs and System.Js which I seems to resolve by specifying Rx.Js in packages
        packages: {
            app: {
                main: '../static/scripts/js/boot.js',
                defaultExtension: 'js'
            },
            rxjs: {
                main: 'Rx.js',
                defaultExtension: 'js'
            }
        }
