### ISSUE TITLE
Getting error after getting html from external location and assigning to a angular variable

### ISSUE THREAD

**Issue by pravinmohite** [apoterenko/ngx-dynamic-template#51]
Getting error after getting html from external location and assigning to a angular variable:-

Following is the console error on browser:-
/------------------start----------------------------------------/

Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'translate' could not be found ("">
    <button  #closeFocus type="button" class="close" (click)="close()" ><span class="sr-only">{{[ERROR ->]'CLOSE' | translate}} </span></button>
    <div class="modal-content">
      <div class="modal-body"): ng:///dynamicComponentModule/dynamicComponentClass.html@1:96
Can't bind to 'pills' since it isn't a known property of 'tabset'. ("
				key messages and discover what you need to do.</h3>

        <tabset [ERROR ->][pills]="true" class="needhelp-securitydevice-tabs">
          <tab title="Overview">
             "): ng:///dynamicComponentModule/dynamicComponentClass.html@8:16
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <tabset [pills]="true" class="needhelp-securitydevice-tabs">
          [ERROR ->]<tab title="Overview">
              <div class="row overview-tab-container">
                <div "): ng:///dynamicComponentModule/dynamicComponentClass.html@9:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
              </div>
          </tab>
          [ERROR ->]<tab title="FAIL PIN">
            <div class="row failpin-tab-container">
              <div class"): ng:///dynamicComponentModule/dynamicComponentClass.html@48:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="PIN not safe">
            <div class="row pinnotsafe-tab-container" aria-atomic="true" "): ng:///dynamicComponentModule/dynamicComponentClass.html@67:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Fail 1,2 or 3">
            <div class="row failonetwothree-tab-container" aria-atomic=""): ng:///dynamicComponentModule/dynamicComponentClass.html@85:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="lock PIN">
            <div class="row lockpin-tab-container" aria-atomic="true" aria-li"): ng:///dynamicComponentModule/dynamicComponentClass.html@105:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Reset PIN">
            <div class="row resetpin-tab-container" aria-atomic="true" aria-"): ng:///dynamicComponentModule/dynamicComponentClass.html@130:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Button">
            <div class="row button-tab-container" aria-atomic="true" aria-live="): ng:///dynamicComponentModule/dynamicComponentClass.html@156:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Battery">
            <div class="row battery-tab-container" aria-atomic="true" aria-liv"): ng:///dynamicComponentModule/dynamicComponentClass.html@173:10
'tabset' is not a known element:
1. If 'tabset' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
				key messages and discover what you need to do.</h3>

        [ERROR ->]<tabset [pills]="true" class="needhelp-securitydevice-tabs">
          <tab title="Overview">
     "): ng:///dynamicComponentModule/dynamicComponentClass.html@8:8
Error: Template parse errors:
The pipe 'translate' could not be found ("">
    <button  #closeFocus type="button" class="close" (click)="close()" ><span class="sr-only">{{[ERROR ->]'CLOSE' | translate}} </span></button>
    <div class="modal-content">
      <div class="modal-body"): ng:///dynamicComponentModule/dynamicComponentClass.html@1:96
Can't bind to 'pills' since it isn't a known property of 'tabset'. ("
				key messages and discover what you need to do.</h3>

        <tabset [ERROR ->][pills]="true" class="needhelp-securitydevice-tabs">
          <tab title="Overview">
             "): ng:///dynamicComponentModule/dynamicComponentClass.html@8:16
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

        <tabset [pills]="true" class="needhelp-securitydevice-tabs">
          [ERROR ->]<tab title="Overview">
              <div class="row overview-tab-container">
                <div "): ng:///dynamicComponentModule/dynamicComponentClass.html@9:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
              </div>
          </tab>
          [ERROR ->]<tab title="FAIL PIN">
            <div class="row failpin-tab-container">
              <div class"): ng:///dynamicComponentModule/dynamicComponentClass.html@48:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="PIN not safe">
            <div class="row pinnotsafe-tab-container" aria-atomic="true" "): ng:///dynamicComponentModule/dynamicComponentClass.html@67:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Fail 1,2 or 3">
            <div class="row failonetwothree-tab-container" aria-atomic=""): ng:///dynamicComponentModule/dynamicComponentClass.html@85:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="lock PIN">
            <div class="row lockpin-tab-container" aria-atomic="true" aria-li"): ng:///dynamicComponentModule/dynamicComponentClass.html@105:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Reset PIN">
            <div class="row resetpin-tab-container" aria-atomic="true" aria-"): ng:///dynamicComponentModule/dynamicComponentClass.html@130:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Button">
            <div class="row button-tab-container" aria-atomic="true" aria-live="): ng:///dynamicComponentModule/dynamicComponentClass.html@156:10
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
          </tab>
          [ERROR ->]<tab title="Battery">
            <div class="row battery-tab-container" aria-atomic="true" aria-liv"): ng:///dynamicComponentModule/dynamicComponentClass.html@173:10
'tabset' is not a known element:
1. If 'tabset' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
				key messages and discover what you need to do.</h3>

        [ERROR ->]<tabset [pills]="true" class="needhelp-securitydevice-tabs">
          <tab title="Overview">
     "): ng:///dynamicComponentModule/dynamicComponentClass.html@8:8
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4200/vendor.bundle.js:64972:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:79017:39)
    at http://localhost:4200/vendor.bundle.js:78937:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:78937:19)
    at http://localhost:4200/vendor.bundle.js:78838:19
    at Object.then (http://localhost:4200/vendor.bundle.js:53850:133)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4200/vendor.bundle.js:64972:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:79017:39)
    at http://localhost:4200/vendor.bundle.js:78937:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:78937:19)
    at http://localhost:4200/vendor.bundle.js:78838:19
    at Object.then (http://localhost:4200/vendor.bundle.js:53850:133)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6309:31)
    at http://localhost:4200/polyfills.bundle.js:6360:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5963:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:83823:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5962:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:5730:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6123:35)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6029:25)

/------------------end ----------------------------------------/

Following are the files:-

needHelpWithSecurityDevice.component.ts:-

import {Component,Input,ViewChild,ComponentFactoryResolver} from '@angular/core';
import { IDynamicRemoteTemplateFactory } from 'ngx-dynamic-template';
import { TranslateService } from '../../../translate';
import { DomSanitizer} from '@angular/platform-browser';
import { Http} from '@angular/http';
import { DialogComponent, DialogService } from "ng2-bootstrap-modal";
import {TabsModule} from "ng2-tabs";
import {showHide} from '../../../directive/showHide/showHide.directive';
import {ElementRef,Renderer2} from '@angular/core';

export interface NeedHelpWithSecurityDeviceModel {
   title:string;
   message:string;
}

@Component ({
  selector:'need-help-security-device',
  templateUrl: './needHelpWithSecurityDevice.component.html',
})

export class NeedHelpWithSecurityDeviceComponent extends DialogComponent<NeedHelpWithSecurityDeviceModel,boolean> implements NeedHelpWithSecurityDeviceModel {
   @Input() collapse: boolean;
    title:string;
    message:string;
    http:Http;
    isActive:boolean=true;
    needHelpWithSecurityDevice: any = "";
    @Input() url: string;
    @ViewChild('closeFocus') el:ElementRef;
    constructor(http: Http,dialogService:DialogService,private rd: Renderer2,private sanitizer:DomSanitizer) {
        super(dialogService);
        http
      .get('http://localhost:4200/assets/needHelpWithSecurityDevice.html')
      .map(response => response.text())
      .subscribe(html => this.needHelpWithSecurityDevice = html);
      setTimeout(function(){
          console.log(this.needHelpWithSecurityDevice);
      },2000)
    }
    ngOnInit(): void {

     }
     ngAfterViewInit() {
    //  this.el.nativeElement.focus();
    }
    showHideContent() {
      this.isActive=!this.isActive;
    }
    confirm() {
      this.result=true;
      this.close();
    }

}

needHelpWithSecurityDevice.component.html

<ng-template dynamic-template [template]="needHelpWithSecurityDevice"></ng-template>

**Comment by apoterenko** [comment]
You should pass the module with a tabset component to the "extraModules"

[extraModules]="[TabSetModule]"

or pass an option to the

https://github.com/apoterenko/ngx-dynamic-template/blob/master/src/dynamic.module.ts#L24

**Comment by pravinmohite** [comment]
needHelpWithSecurityDevice.component.html

<ng-template dynamic-template [template]="needHelpWithSecurityDevice" [extraModules]="[TabsModule]"></ng-template> 

Getting error after adding above changes related to extraModules
Error: Uncaught (in promise): Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'

Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at http://localhost:4200/vendor.bundle.js:67550:40
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:67527:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:78850:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:79167:31)
    at http://localhost:4200/vendor.bundle.js:14542:95
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:5930:26)
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at http://localhost:4200/vendor.bundle.js:67550:40
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:67527:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:78850:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:79167:31)
    at http://localhost:4200/vendor.bundle.js:14542:95
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:5930:26)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6309:31)
    at http://localhost:4200/polyfills.bundle.js:6360:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5963:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:83823:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5962:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:5730:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6123:35)
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6029:25)

**Comment by apoterenko** [comment]
Is AoT mode disabled?

**Comment by apoterenko** [comment]
" [extraModules]="eModules"

Typescript:

eModules=[...]
