### ISSUE TITLE
Related to issue #51

### ISSUE THREAD

**Issue by pravinmohite** [apoterenko/ngx-dynamic-template#52]
needHelpWithSecurityDevice.component.html

<ng-template dynamic-template [template]="needHelpWithSecurityDevice" [extraModules]="[TabsModule]"></ng-template> 

Getting error after adding above changes related to extraModules
Error: Uncaught (in promise): Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'

Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at http://localhost:4200/vendor.bundle.js:67550:40
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:67527:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:78850:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:79167:31)
    at http://localhost:4200/vendor.bundle.js:14542:95
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:5930:26)
    at syntaxError (http://localhost:4200/vendor.bundle.js:53860:34)
    at http://localhost:4200/vendor.bundle.js:67550:40
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:67527:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:78850:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndAllComponents (http://localhost:4200/vendor.bundle.js:78836:36)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:78768:37)
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAndAllComponentsAsync (http://localhost:4200/vendor.bundle.js:79167:31)
    at http://localhost:4200/vendor.bundle.js:14542:95
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:5930:26)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6309:31)
    at http://localhost:4200/polyfills.bundle.js:6360:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5963:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:83823:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:5962:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:5730:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6123:35)
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6029:25)

**Comment by apoterenko** [comment]
See the comment to the previous ticket. You must pass an imported by typescript modules array, because template has component scope

**Comment by pravinmohite** [comment]
Could you please explain,from my understanding you are asking to add TabsModule in import statement and I have already added that.

The code for needHelpWithSecurityDevice.component.ts:-

import {Component,Input,ViewChild,ComponentFactoryResolver} from '@angular/core';
import { IDynamicRemoteTemplateFactory } from 'ngx-dynamic-template';
import { TranslateService } from '../../../translate';
import { DomSanitizer} from '@angular/platform-browser';
import { Http} from '@angular/http';
import { DialogComponent, DialogService } from "ng2-bootstrap-modal";
import {TabsModule} from "ng2-tabs";
import {showHide} from '../../../directive/showHide/showHide.directive';
import {ElementRef,Renderer2} from '@angular/core';


export interface NeedHelpWithSecurityDeviceModel {
   title:string;
   message:string;
}

@Component ({
  selector:'need-help-security-device',
  templateUrl: './needHelpWithSecurityDevice.component.html',
})

export class NeedHelpWithSecurityDeviceComponent extends DialogComponent<NeedHelpWithSecurityDeviceModel,boolean> implements NeedHelpWithSecurityDeviceModel {
   @Input() collapse: boolean;
    title:string;
    message:string;
    http:Http;
    isActive:boolean=true;
    needHelpWithSecurityDevice: any = "";
    @Input() url: string;
    @ViewChild('closeFocus') el:ElementRef;
    constructor(http: Http,dialogService:DialogService,private rd: Renderer2,private sanitizer:DomSanitizer) {
        super(dialogService);
        http
      .get('http://localhost:4200/assets/needHelpWithSecurityDevice.html')
      .map(response => response.text())
      .subscribe(html => this.needHelpWithSecurityDevice = html);
      setTimeout(function(){
          console.log(this.needHelpWithSecurityDevice);
      },2000)
    }
    ngOnInit(): void {

     }
     ngAfterViewInit() {
      this.el.nativeElement.focus();
    }
    showHideContent() {
      this.isActive=!this.isActive;
    }
    confirm() {
      this.result=true;
      this.close();
    }

}

**Comment by apoterenko** [comment]
See the live example
https://github.com/apoterenko/ngx-dynamic-template/blob/master/demo/src/app/dynamic/dynamic-holder.component.html#L27
